version: "3.9"
services:
  backend:
    container_name: backend_service
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/var/www/app/backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend_db
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/api/test"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5

  backend_db:
    container_name: backend_db
    image: mariadb:10.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: fusion
    ports:
      - "9906:3306"
    volumes:
      - fusion_maridb_data:/var/lib/mysql

  frontend:
    container_name: frontend_service
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/var/www/app/frontend
      - /var/www/app/frontend/node_modules
    ports:
      - "4000:4000"

  web_proxy:
    container_name: web_proxy
    build: ./nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - .env

networks:
  default:
    name: fusion

volumes:
  fusion_maridb_data:
