name: CI Precheck

on:
  push:
    branches-ignore:
      - main

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd frontend
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend"
      - run: npm ci
        working-directory: frontend
      - run: npm run lint:check
        working-directory: frontend

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd frontend
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend"
      - run: npm ci
        working-directory: frontend
      - run: npm run format:check
        working-directory: frontend

  golint:
    name: Run GoLint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: backend
          args: --config .golangci.yml

  gosecurity:
    name: Run Security check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: ellogroup/gosec-action@v1
        with:
          working-directory: backend
          go-install: true
          go-version: "1.21"
          go-version-file: "backend/go.mod"
          go-cache-dependency-path: "backend/go.sum"
