name: CI Testing

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  Precheck:
    uses: ./.github/workflows/precheck.yml
  test:
    name: Run Playwright Tests
    needs: Precheck
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "frontend"
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
        env:
          HOME: /root
